# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.progletariat.com
gitlocation: https://github.com/codehutch/codehutch.github.io.git
gitbranch: master
title: Progletariat
subtitle: There isn't a subtitle
description: A term used to describe the class of wage-earners in a capitalist society whose only skill of any perceived value is their ability to create computer software.
source: ../BlogContent/
blog: ../BlogContent/blog/
blogIndex: ../BlogContent/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: ../Output/
deploy: deploy
themes: themes
