# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.progletariat.com
gitlocation: https://github.com/codehutch/codehutch.github.io.git
gitbranch: master
title: Progletariat
description: >
    Progletariat /ˌproʊglɪˈtɛəriːət/: A term used to describe the class of wage-earners (especially programmers) in a
    capitalist society whose only possession of any perceived value is their labour-power (their ability to code).
source: source/
blog: source/blog/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes